# This workflow is a reusable one called by other workflows
name:  CLI/UI template

on:
  workflow_call:
    # Variables to set when calling this reusable workflow
    inputs:
      ca_type:
        required: true
        type: string
      cert-manager_version:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      cluster_number:
        required: true
        type: string
      cluster_namespace:
        required: true
        type: string
      cluster_type:
        required: true
        type: string
      cypress_tags:
        required: true
        type: string
      destroy_runner:
        required: true
        type: boolean
      k8s_downstream_version:
        required: true
        type: string
      k8s_upstream_version:
        required: true
        type: string
      node_number:
        required: true
        type: string
      proxy:
        required: true
        type: string
      public_domain:
        required: true
        type: string
      public_fqdn:
        required: true
        type: string
      qase_project_code:
        required: true
        type: string
      qase_run_id:
        required: true
        type: string
      rancher_upgrade:
        required: true
        type: string
      rancher_version:
        required: true
        type: string
      runner_label:
        required: true
        type: string
      selinux:
        required: true
        type: boolean
      sequential:
        required: true
        type: boolean
      test_type:
        required: true
        type: string

    # Job outputs to export for caller workflow
    outputs:
      steps_status:
        description: Status of the executed test jobs
        value: ${{ join(jobs.*.outputs.steps_status, ' ') }}

    # Secrets to set when calling this reusable workflow
    secrets:
      credentials:
      qase_api_token:

jobs:
  airgap:
    if: ${{ inputs.test_type == 'airgap' }}
    uses: ./.github/workflows/airgap.yaml
    secrets:
      credentials: ${{ secrets.credentials }}
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      cert-manager_version: ${{ inputs.cert-manager_version }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      rancher_version: ${{ inputs.rancher_version }}
      runner_label: ${{ inputs.runner_label }}
      test_type: ${{ inputs.test_type }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}
